add_test(NAME test-discover-ble COMMAND "test-discover-ble")
add_test(NAME test-discover-serial COMMAND "test-discover-serial")
add_test(NAME test-read-serial COMMAND "test-read-serial")
add_test(NAME test-read-ble COMMAND "test-read-ble")
add_test(NAME test-pair-ble COMMAND "test-pair-ble")
add_test(NAME test-unpair-ble COMMAND "test-unpair-ble")
add_test(NAME test-write-serial COMMAND "test-write-serial")
add_test(NAME test-is-serial-meshtastic COMMAND "test-is-serial-meshtastic")
