#!/bin/sh
#
#	Usage:
#	./generate-code
#	./generate-code SOURCE-PATH
#
if [ -n "$1" ]; then
    cd $1
fi

DT=`date --rfc-2822`
SRC=.

mkdir -p $SRC/gen

OPTS="--experimental_allow_proto3_optional"

protoc $OPTS -I $SRC/third-party/proto --cpp_out=$SRC/gen third-party/proto/nanopb.proto
PROTO_DIR=third-party/proto/meshtastic
for proto in $PROTO_DIR/*.proto; do
	proto=$(basename "$proto")
	protoc $OPTS -I $SRC/third-party/proto --cpp_out=$SRC/gen $PROTO_DIR/$proto
done
